### ISSUE TITLE
MD5 hash doesn't match content

### ISSUE THREAD

**Issue by klu2** [structurizr/java#10]
After upgrading to structurizr 0.3.0, I'm getting the following debug message on structurizrClient.mergeWorkspace:

Mai 11, 2015 10:03:21 PM com.structurizr.api.StructurizrClient debugResponse
INFORMATION: HTTP/1.1 401 Unauthorized
Mai 11, 2015 10:03:21 PM com.structurizr.api.StructurizrClient putWorkspace
INFORMATION: {"message":"MD5 hash doesn't match content"}

API-Token is correct for sure, I'm using workspace ID 111

**Comment by simonbrowndotje** [comment]
The API key/secret will be correct, as that gets validated before the MD5 hash of the content (JSON) being sent. Does the previous version of the client library still work?

**Comment by klu2** [comment]
no, it also doesn't work with 0.2.1, same issue

**Comment by simonbrowndotje** [comment]
I've had a look into this and I'm slightly stumped as to what the problem could be. I'm wondering whether there is a character encoding mismatch here somewhere. If the code generating your model is standalone (i.e. not extracting components from a codebase), would you be able to send it to me via e-mail?

**Comment by simonbrowndotje** [comment]
I think I've found the problem ... I wasn't being explicit with the character encoding when creating (and base64 encoding) the MD5 hash of the JSON. I can recreate the same error message by starting the JVM with a character encoding that is not UTF-8 ... e.g. -Dfile.encoding=ISO8859_1

I've pushed a version 0.3.1 to jCenter with a fix.
