### ISSUE TITLE
DotWriter/GraphViz too limited to visualize workspace?

### ISSUE THREAD

**Issue by victorvogelpoel** [structurizr/java#102]
I decided to take a stab at C4 and work out a workspace. I was already using GraphViz and Dot for automatically generated graph visualizations and was hoping that a C4 workspace can visualized using Dot/GraphViz. I find that the DotWriter spits out dot content just fine, but that GraphViz cannot create a complete image for a more complex workspace... Is that your experience as well?
I was hoping for GraphViz to visualize all the defined views in the workspace in one image, but only the first digraph ends up in the image. Online GraphViz versions confirm the behavior.

Working with the .NET framework, I ported your Java DotWriter to C# (easy) and did a crude port of  Java LivingDocumentation.DotDiagram to C# (harder). Then I used one of your example workspaces, Big Bank plc, to try out the ported DotWriter/DotDiagram and found that the dot content contains several digraphs, but GraphViz only visualizes the first one...

**Comment by simonbrowndotje** [comment]
The DotWriter produces one diagram definition per system context, container and component view defined in the workspace (i.e. one digraph per view); see [this gist for an example](https://gist.github.com/simonbrowndotje/7135acf75bfdb39d290685efbc480e34). I don't think you can feed the entire output to graphviz in one go though, which is probably why you're only seeing a single diagram.

**Comment by victorvogelpoel** [comment]
I figured as much.

Next up: trying structurizr as the visualizr.

**Comment by simonbrowndotje** [comment]
It depends what your requirements are, but the PlantUML writer in conjunction with something like [docToolchain](https://github.com/docToolchain/docToolchain) might be worth a look. But yes, Structurizr will certainly give you some other options for visualising workspaces, and navigating between diagrams. I will close this issue if that's okay?

**Comment by victorvogelpoel** [comment]
Currently I want clean simple visualizations of the C4 workspace model for a software system I inherited. 
I'll take a look at docToolchain.
Closing the issue is ok.

Is it worth publishing the .NET port of LivingDocumentation.DotDiagram and DotWriter for Structurizr?
