### ISSUE TITLE
IllegalArgumentException in AdrToolsImporter while parsing DecisionStatus

### ISSUE THREAD

**Issue by mcbeelen** [structurizr/java#108]
We have an application, which generates the diagrams, populates the documentation and parses the ADRs. When I run locally everything works fine, but when it runs on our build-server or at a co-workers computer. the application fails due to a IllegalArgumentException.

```
Caused by: java.lang.IllegalArgumentException: No enum constant com.structurizr.documentation.DecisionStatus.
 	at java.lang.Enum.valueOf(Enum.java:238)
 	at com.structurizr.documentation.DecisionStatus.valueOf(DecisionStatus.java:6)
 	at com.structurizr.documentation.AdrToolsImporter.extractStatus(AdrToolsImporter.java:142)
        at com.structurizr.documentation.AdrToolsImporter.importArchitectureDecisionRecords(AdrToolsImporte/.java:83)
```

Based upon the stacktrace I concluded that actual name of the DecisionStatus does not get returned from the statusRegex matcher.group(1). I assume it return an emptyString.

The most apparent difference is that I use a Mac and the build-server and my co-worker run Windows as the OS. I will try to troubleshoot this some further.

Using: Structurizr 1.0.0-RC7

**Comment by simonbrowndotje** [comment]
I imagine it's related to this -> https://github.com/structurizr/java/commit/491753ffa4f565c4e371ce65a0408d67543e3b51

**Comment by simonbrowndotje** [comment]
v1.0.0 is just releasing to Maven Central, so hopefully upgrading will fix your problem.

**Comment by simonbrowndotje** [comment]
I don't think so -> https://github.com/structurizr/java/compare/1.0.0-RC7...master

**Comment by mcbeelen** [comment]
@simonbrowndotje : You are right.
The problem does not occur anymore after the upgrade to 1.0.0
