### ISSUE TITLE
IllegalArgumentException: A component type must be provided

### ISSUE THREAD

**Issue by joaoe** [structurizr/java#109]
Hi.
When running `ComponentFinder.componentFinder` I get my log littered with warnings, e.g:
```
2018-10-31 09:17:50.980 [main] WARN  com.structurizr.analysis.AbstractComponentFinderStrategy - java.lang.IllegalArgumentException: A component type must be provided.
```

As far as I've debugged, the exception comes from here https://github.com/structurizr/java/blob/master/structurizr-core/src/com/structurizr/model/Container.java#L163
and is logged here
https://github.com/structurizr/java/blob/master/structurizr-analysis/src/com/structurizr/analysis/AbstractComponentFinderStrategy.java#L135

The problem are all the calls to `Container.getComponentOfType` using `Class.getCanonicalName()` as argument, since the latter can return `null` in a number of cases, like anonymous and local classes. For instance, for class `ch.qos.logback.core.subst.Tokenizer$1`.

So, you should null check `getCanonicalName()` and ignore those classes or perhaps use the `!isNestedClass(type)` check, which is used in another place in the file.

**Comment by simonbrowndotje** [comment]
Thanks, I've added the ```isNestedClass(type)``` check.
