### ISSUE TITLE
Cannot upload to Structurizr API using Java 11: SSLHandshakeException: Received fatal alert: handshake_failure

### ISSUE THREAD

**Issue by gdubya** [structurizr/java#111]
This isn't a problem with Structurizer, per se, but calls to the Structurizer API fail when using Java 11 due to missing (?) certs in the OpenJDK distribution (discussed more here: https://www.reddit.com/r/java/comments/8y2hpj/openjdk_missing_certificates/e29lg4s).

This could be resolved by changing the certs used by api.structurizr.com, or by adding the certs to one's own JDK. 

Tested using OpenJDK Java 11.0.1

Workaround: Downgrade Java to 1.8, then the examples work fine :+1:

**Comment by simonbrowndotje** [comment]
Thanks for letting me know. The cert installed at api.structurizr.com is a CloudFlare issued certificate, so hopefully this will get resolved further upstream at some point as it will likely impact a lot of other sites.

**Comment by gdubya** [comment]
Oh, Cloudflare? Then if it was a general Java 11 problem I would have expected a much bigger fuss by now. 

Looks like the problem is actually a compatibility issue with the HttpComponents dependency. Upgrading this to the latest release (currently 5.0 beta) should resolve the issue.

See https://hc.apache.org/news.html#a22_October_2018_-_HttpComponents_HttpCore_5.0-beta5_released

**Comment by jkubrynski** [comment]
Can you please release the 1.1.1? Current version doesn't work with Java11, which doesn't make sense as the fix is already in the master branch

**Comment by simonbrowndotje** [comment]
v1.2.0 is now being released to Maven Central.
