### ISSUE TITLE
SSL exception

### ISSUE THREAD

**Issue by devharis** [structurizr/java#118]
After registering a new account and trying to run GettingStarted.java example with my own credentials as apikey and apisecret we get this error when it tries to perform `structurizrClient.putWorkspace(WORKSPACE_ID, workspace);`

```
SEVERE: javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
Exception in thread "main" com.structurizr.api.StructurizrClientException: javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated
        at com.structurizr.api.StructurizrClient.putWorkspace(StructurizrClient.java:308)
        at com.documentation.App.main(App.java:43)
```

**Comment by simonbrowndotje** [comment]
Do you have more details? Is this the Structurizr cloud service, or an on-premises installation? Which version of Java? OpenJDK, Oracle, etc? Are you behind a corporate firewall that is potentially intercepting SSL traffic, or are you directly connected to the Internet? Is there a proxy server? Is this a "locked down" JDK with a custom keystore?

**Comment by devharis** [comment]
Seems this got resolved by upgrading from implementation (group: 'com.structurizr', name: 'structurizr-client', version: '1.1.1') -> implementation (group: 'com.structurizr', name: 'structurizr-client', version: '1.2.0').
