### ISSUE TITLE
SourceCodeComponentFinderStrategy don't work with Kotlin code

### ISSUE THREAD

**Issue by Kinmarui** [structurizr/java#120]
maybe I'm missing something obvious but it appears that current implementation doesn't support Javadocs in Kotlin files mainly because com.sun.tools.javadoc.Main.execute don't support Kotlin files. I tried looking for alternatives (dokka, Asciidoclet) but I found nothing that could be easily used.

Maybe I'm just missing something? This can be considered both feature request and request for help since I may try to implement it myself if I'm pointed in right direction.

**Comment by simonbrowndotje** [comment]
Correct, there is currently no support for Kotlin. If dokka, etc don't provide support for programatically extracting doc comments, you could parse the source files and extract the relevant content. That's not a particularly pretty approach, but it could certainly work.
