### ISSUE TITLE
OSGi compatibility of Structurizr Java releases 

### ISSUE THREAD

**Issue by ideas-into-software** [structurizr/java#123]
Hi, 

I wanted to use Structurizr Annotations in a project I put together recently (https://github.com/ideas-into-software/automated-linguistic-analysis). 

Unfortunately, releases of Structurizr Java libraries currently are not OSGi compatible - required headers are missing from their manifests.

Since I'm using BND via Maven to build and package this OSGi application, with at least 10+ Maven modules where Structurizr annotations were to be used, wrapping this library as OSGi bundle required creating a new version of 'structurizr-annotations' library, only to have the proper manifest generated, then referencing this new version in main POM, i.e.: 

    (...)
    <dependency>
      <groupId>com.structurizr</groupId>
      <artifactId>structurizr-annotations-osgi</artifactId>
      <version>${structurizr.version}</version>
    </dependency>
    (...)

The problem with this solution is I cannot release a project which depends on unreleased artifacts such as 'structurizr-annotations-osgi' and embedding the same non-OSGi compatible version of released library (https://mvnrepository.com/artifact/com.structurizr/structurizr-annotations) in 10+ different Maven modules' (via their lib directories) is not really a good alternative as it requires too much duplication.

Is it possible to have future releases of Structurizr Java libraries have the necessary manifest headers so they're OSGi compatible out-of-the-box? 

Regards,

**Comment by simonbrowndotje** [comment]
Thanks, I've just pushed a commit (https://github.com/structurizr/java/commit/387e4f8f8b6d50e8343b6467e57bbe2841ec98c8) that should add the required headers. Does that look okay?

**Comment by ideas-into-software** [comment]
Hi, 

The 'Bnd Builder Gradle Plugin' (https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd.gradle/README.md) I suggested would take care of any required export/import headers in manifests; doing this manually is tricky, since forgetting such header will render resulting bundle not compatible for OSGi, e.g. during resolution.

The build.gradle you added was done manually - it's almost perfect; please see GIST I created: https://gist.github.com/ideas-into-software/fa93bf4448198ea690e7f051276f7a86

With build.gradle like in GIST I linked to, 'structurizr-annotations' is resolved properly / ready for OSGi. 

Kind regards,

**Comment by simonbrowndotje** [comment]
Thanks! I'll do a release onto Maven Central later this week.

**Comment by ideas-into-software** [comment]
Hi Simon. I see you closed this issue but no releases in https://mvnrepository.com/artifact/com.structurizr since March. You mentioned you'd push a new release back in may, does closing this one mean you're about to cut a new one soon? 
Regards,
Michael

**Comment by simonbrowndotje** [comment]
The release is currently happening onto Maven Central, so the artifacts should appear shortly.

**Comment by simonbrowndotje** [comment]
There's a problem with files syncing to Central -> https://status.maven.org/incidents/vmq35qzd8gxw?u=w28ndb3cdfly
