### ISSUE TITLE
ContainerInstance vs DeploymentNode?

### ISSUE THREAD

**Issue by toorog** [structurizr/java#126]
How do I model a Container that can have multiple configurations for deployments?
Is the deployment configuration either attached to the Container Instance, the Container, or to a Deployment Node that hosts the container?

Example:
I have a microservice that is deployed two times under different subdomains. During deployment I configure the microservice for the given environment. Lets say Deployment A shows a black website, Deployment B a white one.

Where do I attach the property "Background Color"? Do I use two containers "Container A" and "Container B", or do I add this property to the containers instance, or even to an "Artificial" Deployment container?

**Comment by maxvar** [comment]
In such case I as a model user would prefer to see two containers built from the same component (microservice) + two different configs and deployed to two nodes (probably in two environments). And the "background color" will describe the containers.
