### ISSUE TITLE
Json Schema - Implementation Validation

### ISSUE THREAD

**Issue by toddmeinershagen** [structurizr/java#13]
I would like to have a [json schema](http://jsonschema.net/#/) to be generated from the current code to allow other implementations (.NET, ruby, php, etc.) to be able to keep up-to-date with the latest object model of the REST api for the [Structurizr site](https://www.structurizr.com).  

I will issue a pull request for this issue with my first cut of this.

Thanks.

**Comment by emicklei** [comment]
+1 . I would like to create a Go client to document my systems

**Comment by simonbrowndotje** [comment]
Now the API has stabilised, I'm looking at options to document it. Any thoughts on Swagger, Apiary, etc over JSON Schema?

**Comment by emicklei** [comment]
I worked a lot with Swagger (Java and Go) and the new 2.0 would be my suggestion.

**Comment by toddmeinershagen** [comment]
I am fine with Swagger.  It has a lot of support on the .NET side with the Azure API Management supporting import of a Swagger file for REST endpoints.

**Comment by simonbrowndotje** [comment]
This is still a work in progress (the views and styles properties of the workspace are not yet documented), but I've added the source for a Swagger definition to this repo -> https://github.com/structurizr/java/blob/master/swagger.txt

I'll host the resulting JSON on api.structurizr.com at some point.

**Comment by simonbrowndotje** [comment]
It doesn't include the authentication mechanism, but I think this [Swagger JSON](https://api.structurizr.com/swagger.json) covers the JSON schema for Structurizr workspaces.

**Comment by simonbrowndotje** [comment]
Just to close this issue, an OpenAPI 3.0 specification can be found here -> https://structurizr.com/help/web-api
