### ISSUE TITLE
PlantUMLWriter should write one file per view

### ISSUE THREAD

**Issue by Riduidel** [structurizr/java#133]
Current mode, where all views are written in the same file, make inclusion of generated diagrams hard in some tools (typical example is Asciidoc-diagram, which requires one file per diagram)

**Comment by simonbrowndotje** [comment]
There's a ```toString()``` method that returns an array if that helps? See https://github.com/structurizr/java/blob/master/structurizr-plantuml/src/com/structurizr/io/plantuml/PlantUMLWriter.java#L177

**Comment by Riduidel** [comment]
Well, indeed, there is, but we also loose the diagram ids (which would
be good filenames), since this toString method splits the "mega"
workspace plantuml file.

Well, it seems like I could parse the first line to get back the id :-)

Le 21/10/2019 à 22:49, Simon Brown a écrit :

**Comment by Riduidel** [comment]
OK, I've added the code to reexport the diagram id from the generated
plantuml, and now it works !

Le 21/10/2019 à 22:49, Simon Brown a écrit :

**Comment by simonbrowndotje** [comment]
I've added a new method for you to use -> https://github.com/structurizr/java/blob/master/structurizr-plantuml/src/com/structurizr/io/plantuml/PlantUMLWriter.java#L207

**Comment by Riduidel** [comment]
Awesome ! It's exactly what I need (instead of extracting the diagram key from the generated PlantUML).
Do you have any planned release for that component ?

**Comment by simonbrowndotje** [comment]
Probably next week sometime ... I have some other things to put into a release.
