### ISSUE TITLE
feature proposal: add URL to relations

### ISSUE THREAD

**Issue by maxvar** [structurizr/java#141]
Hi, many thanks for your great work!
One of the useful features that link the visualization to documentation are URLs on elements.
Why there is no such thing on relations? Aren't arrows no less significant than boxes?) Am I missing something and there a better way from a depicted relation to the corresponding detailed description of the protocol and data contents? Or is that a design decision not to do such a thing?

**Comment by simonbrowndotje** [comment]
Thanks for the suggestion! That's been added to the client library, and will be supported on the Structurizr service in the next couple of days.
