### ISSUE TITLE
some urls created with client are missing from views

### ISSUE THREAD

**Issue by maxvar** [structurizr/java#146]
Hi, i'm trying the new support for URLs on relations and find that some links are not shown in the views. They are also missing from json file (which is retrieved by client from the server).
Tested with java client 1.3.4 against build 1795 (both structurizr.com  and on-premise version).
I no not see anything outstanding with the links which are dropped.

**Comment by simonbrowndotje** [comment]
Feel free to raise a ticket while signed in to the cloud service (include your workspace ID), and I'll take a look at the workspace. Please also include a note about which URLs are not showing up. Thanks!

**Comment by maxvar** [comment]
Simon, thanks for the prompt response! I took some time to create a sample project to isolate the issue and found the culprit.  That was [сertainly] myself with some misplaced `apply`'s in kotlin code.

**Comment by simonbrowndotje** [comment]
You're welcome, thanks for letting me know!
