### ISSUE TITLE
how do I provide tech details for an external system to show in Deployment View?

### ISSUE THREAD

**Issue by maxvar** [structurizr/java#150]
Deployment views are ideal to communicate with enterprise infrastructure and infosec people about network routes and rules and ACLs.
Still when MySystem connects to an external system on the internet I have to create an artificial container for the external system, giving it some tech details and then place it on an artificial external deployment node (of which I usually know nothing but fqdn).
This way the deployment view properly shows the connection of one of my system's container with the external system.
Is there a simpler way or this is the only _proper_ way? 
(I cannot just drop the system on a node and only deployed elements are shown on a deployment view.)

**Comment by simonbrowndotje** [comment]
You're correct, the current deployment view in Structurizr doesn't allow you to show container to software system dependencies; that's what the container view is for. Adding people and software systems to deployment views is certainly possible, but needs some thought...

**Comment by maxvar** [comment]
I do not see how *people* will be useful for deployment view (until there are enough implants in the populace, maybe?)
Now I just add a whole system to a node and that places all of its containers on that node, thanks to Kotlin which allows me to "extend" `DeploymentNode`. Maybe that feature can be useful for a wider java userbase.
Still, manually adding an extra container to an external system (of which I know next no nothing) seems unneeded.

**Comment by simonbrowndotje** [comment]
The current deployment view is designed to show the mapping of containers to infrastructure, and typically people only use this for the containers that are inside the boundary of the software system they are building/documenting.

What's your use case for showing external dependencies, when these can already be shown on the container diagram?

**Comment by maxvar** [comment]
My container diagrams typically show protocols and logical connections of contaoners, but lack real hosts and networks addresses (hostnames or ip's), so they are not enough to talk to infosec. My deployment views add those together with fail-overs and clustering, but force me to add some made-up details.

**Comment by simonbrowndotje** [comment]
This is a work in progress, but I'm adding support for including software systems on deployment views. For example...

![structurizr-1-DevelopmentDeployment (1)](https://user-images.githubusercontent.com/1009874/89179437-98dad180-d587-11ea-980a-579ee0487625.png)

**Comment by simonbrowndotje** [comment]
This feature is now available in v1.5.0 ... which is being released now.
