### ISSUE TITLE
PlantUML: styles not applied in deployment view

### ISSUE THREAD

**Issue by rzabini** [structurizr/java#151]
In the following sample I would expect the line between the two containers in the deploymen view to be solid red.

This happens in https://structurizr.com/dsl by choosing the "Strcturizr" option, but not with the "PlantUML" option: the line is dashed and grey (the same happens by exporting the model in "Structurizr CLI 1.3.0").

The same line between a user and a software system is drawn just fine, so it seems a problem of the deployment view only.

```
workspace "Deployment only" {

    model {
        softwareSystem = softwareSystem "Software System" "My software system." {
                    container1 = container "C1"
                    container2 = container "C2"

        }

        container1 -> container2 "Uses" "" "red"
        deploymentEnvironment "Live" {
            deploymentNode "Server" {
                containerinstance container1
                containerinstance container2
            }
        }
    }

    views {
        deployment * Live {
            include *
            autoLayout          
        }

        styles {
            element "Software System" {
                background #1168bd
                color #ffffff
            }
            
            relationship "red" {
                color #ff0000
                dashed false
            }
        }
    }    
}
```

**Comment by simonbrowndotje** [comment]
Thanks! This is fixed on [structurizr.com/dsl](https://structurizr.com/dsl), and will be rolled out to the CLI over the next day or so.

![](http://plantuml.com/plantuml/img/hL9DJm8n4BttLqpMYnusBYJiHh9iG8mdzOB60t2eT5WQkfrDMxuq_dVRXIZ643quJNfuCs_Uwqpxrd7ZLfKwbw9t9zSOts2jQ5UXTXVCIQSGlX288TGmPfTIrzpm2juOW5rmGHkfIvXpPT4Zt1ZQt99s8_cAq4ey973ELyezujODb2nrqs_cBpG-kp6yVfR2BQ2TXEgAR-_HMbxYeKF2tjb22WJh2KXkLoDpL8CZU27dg08X3SwS97taJfF0FEyKHUFpci-MfQ6L5aDIPE1iteJF1Ai7B6aYL9CHQBwZxqUzWnhNfV82wIa1qSHV1Au6uPmIoFvH8Cm4eX6QDPg97Xzjzy5dfX7i1yOjT1hDJniGzNh3raJdrg-asqgAyT2BSgdHJFFB01Q1dEx9wGzg-rTgjgTctcKAyTZl9xna6XUGGHUY9uisOdtKmd_O3m00)
