### ISSUE TITLE
Use fluent API with chaining to improve readability and simplify usage

### ISSUE THREAD

**Issue by filipowm** [structurizr/java#152]
Currently Structurizr has "standard" API, e.g. 
```java
system = model.addSoftwareSystem("My system", " It's descritpion");
system.setLocation(Location.Internal);
system.addTags("t1", "t2");
container = system.addContainer("name", "desc", "technology");
relationship = container.uses(otherContainer, "interacts with");
```

Would be nice to be able to simplify it using Fluent API approach:
```java
system = model.addSoftwareSystem("My system", "It's description")
          .location(Location.Internal)
          .tags("t1", "t2")
          .addContainer("name", "desc", "technology")
                  .tags("t3")
                  .uses(otherContainer, "interacts with").and()
                  .uses(andAnotherContainer, "also interacts with").and().and()
          .addContainer("name2", "desc2", "fancy tech").and();
```

Then to access / modify some property:
```
system.container("name")
               .relationship("rName")
               .setUrl("http://localhost")
```

I think the way fluent api is implemented shouldn't impact existing code, thus should be backward compatible. And for setters (not nested objects) methods should be easy to change (e.g. `setUrl`, `addTags`).

**Comment by simonbrowndotje** [comment]
I think a better approach would be to write a fluent wrapper around the core library, much like some of the Kotlin DSLs have done. This gives you a blank slate to do whatever you want, and you're pretty much unencumbered by the current API. I do like the idea of a fluent API, I'm just not sure that modifying the existing core library is the best way to do that.

**Comment by filipowm** [comment]
> I think a better approach would be to write a fluent wrapper around the core library, much like some of the Kotlin DSLs have done. This gives you a blank slate to do whatever you want, and you're pretty much unencumbered by the current API. I do like the idea of a fluent API, I'm just not sure that modifying the existing core library is the best way to do that.

That makes sense. Then it seems the best approach would be to make it as an extension and place here: https://github.com/structurizr/java-extensions . I already started drafting some code, so when I'll feel it's in a pretty good shape, I could make a PR in that repo to share some draft implementation.
