### ISSUE TITLE
Allow relationships in DynamicView to go both ways without two relationships between Elements in Model

### ISSUE THREAD

**Issue by fridgebuzz** [structurizr/java#153]
In a dynamic view, whether it's a structurizr dynamic view, a UML communication/collaboration view, or a sequence diagram, it's often desirable to see the response to a request being returned (so that you can see precisely when it happens in the flow of events). Currently, doing this requires that there be two relationships between Elements (say Containers), one in each direction, or else the dynamic view will not be created. However, this means adding relationships to the Container diagram which are not desirable. 

It's not clear what the best way to solve this might be, since relationships in the model are directed. It's not enough to allow the dynamic view relationship if a model relationship exists in either direction. 

If there are workarounds I'm unaware of, please let me know. One brute-force method that might work is to style the redundant relationships in the Container diagram so they're invisible, though that seems a nasty hack. Any directional advice is welcome. I'm willing to throw together a solution, however I'm aware it has to be compatible with the structurizr service, which might constrain a solution.

Note there is an outstanding PR for a similar issue, here: https://github.com/structurizr/java/pull/130 It's not clear if this is a viable solution or not, but it does suggest that the problem affects more than just me ;)

**Comment by simonbrowndotje** [comment]
This is now available in v1.5.0 (which is being released now).

**Comment by fridgebuzz** [comment]
Thank you!

**Comment by alleknalle** [comment]
@simonbrowndotje would it be an idea to be able to change the styling of the response relationship to make a visual difference between the 'regular' relation direction and the response?
