### ISSUE TITLE
Positioning of Elements based on relations

### ISSUE THREAD

**Issue by GianniGiglio** [structurizr/java#155]
Hi,

I was wondering if there is a way to code the position of elements.
In the generated puml file you have relations defined as follow:

Rel_D(3, 2, "")

In this case, the D stands for down. You can also set-it to up, left or right.

Any way this can be done programmatically?

**Comment by simonbrowndotje** [comment]
Unfortunately not.

**Comment by GianniGiglio** [comment]
Ok thank you closing the issue.
