### ISSUE TITLE
idGenerator since version 1.6.0

### ISSUE THREAD

**Issue by guillemcanal** [structurizr/java#156]
Hi @simonbrowndotje,

Since version `1.6.0`, it seems that 2 alternative implementations of `IdGenerator` were removed (namely `MessageDigestIdGenerator` and `NormalizedNameIdGenerator`). What exactly motivated their removal ? Does custom implementations of `IdGenerator` are discouraged ? 2 years ago, when I was using structurizr.com in another company, the `SequentialIntegerIdGeneratorStrategy` implementation was problematic: During the reconciliation phase, when new elements were added to the model, page layouts of views referencing those new elements were messed up. Is it still an issue today ? 

Thank you :)

**Comment by simonbrowndotje** [comment]
I removed them because I didn't want to support custom implementations as a part of the core library ... but you should still be able to plug in your own ID generators.

**Comment by guillemcanal** [comment]
Oh I see, so I assume that custom implementations are still safe to use when targeting structurizr.com as a rendering engine ?

Thank you again, I don't want to appear ungrateful and annoyed about the removal, I'm legitimately curious about the change, the library is amazing as it is 🎉

**Comment by simonbrowndotje** [comment]
The honest answer is that I don't know whether custom implementations will work ... but I don't see why they wouldn't. Another approach is to define your own custom `LayoutMergeStrategy` on a view by view basis, to fine tune how the local and remote layouts are merged.

**Comment by guillemcanal** [comment]
Thanks for the suggestion, I'll look into it 👍
