### ISSUE TITLE
Usage in a Gradle multi module-project

### ISSUE THREAD

**Issue by MLNW** [structurizr/java#157]
I am trying to use Structurizr with a multi-module Gradle project. Its structure is as follows:

```
.
├── buildSrc
├── documentation
│   ├── decisions
│   └── model
└── services
	├── api-gateway
	├── service-a
	├── service-b
	├── service-c
	├── service-d
	└── service-e
```

The idea is to have a documentation module with ADRs and a module that generates the Structurizr model and a set of services, which represent the containers within the model.

Now I am struggling to make this work.
Following your suggestions at https://github.com/structurizr/java/blob/master/docs/usage-patterns.md I first tried to create multiple programs (with separate main functions) within the model and each service tasked with creating their part of the model.
These main functions would then be called as `JavaExec` tasks during the build and generate an artifact.

There are multiple issues with this approach:
1. How to get the base model to each service for enhancement?
1. How to get the changes made by a service back so that another service actually builds upon them?
1. How to get the final model with all service changes back to the model module to generate PDFs from all views?

I started to create custom Gradle tasks in the `buildSrc` directory for each required step, but the issues outlined above remain.
These steps would include:
1. Build the base model
1. Enhance an existing model with component scans and view definitions
1. Generate PDFs for all views contained in the model

Do you have any suggestions on how to accomplish this? Help would be greatly appreciated!

**Comment by simonbrowndotje** [comment]
> 1. How to get the base model to each service for enhancement?
> 2. How to get the changes made by a service back so that another service actually builds upon them?

I typically do something like this:

Program1
```
SoftwareSystem ss = workspace.getModel().addSoftwareSystem("X");
...
WorkspaceUtils.saveWorkspaceToJson(workspace, new File("workspace.json"));
```

Program2
```
Workspace workspace = WorkspaceUtils.loadWorkspaceFromJson(new File("workspace.json"));
SoftwareSystem ss = workspace.getModel().getSoftwareSystemWithName("X");
...
```

I'd recommend not over-complicating things. If all of those services are a single software system, in a single repo, and you want a single set of documentation, then perhaps a well-modularised single program is easier. Also, if you're not planning on using Java code to create parts of the model programmatically (e.g. parsing log files, using reflection to find components, etc), then the DSL might be easier, since it supports [includes](https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#includes).

> 3. Generate PDFs for all views contained in the model

I can't help there I'm afraid - it depends which toolchain you're using to generate diagrams.

**Comment by MLNW** [comment]
The main idea with this approach would be to use reflection to find the components and create a living document with that.
This would have to be done in each service which is part a single software system.
I have already used the DSL for an upfront design but I would like to use code for the further life time of the project.

Regarding the PDF generation: I have already solved that task. The real issue lies in the coordination between services and documentation.

**Comment by MLNW** [comment]
After a day of trying to make this work, I came up with two possible ways to solve the issue. Though I wasn't able to get either of them to work out for me:

1. In the documentation module pull in each service JAR as a dependency and scan the components in a central task
    - This is based on the comments from [this issue](https://github.com/structurizr/java/issues/58#issuecomment-341573628)
    - I tried to pull in one of the service JARs (which is built with the Spring Boot Gradle plugin) and scan its components but the `ComponentFinder` did not find any components
    - I guess I didn't get the right dependency or there is a more fundamental problem with my approach
    - This also seems to be problematic when trying to use the `SourceCodeComponentFinderStrategy` since the source directory would be in another project
    ```
	dependencies {
		implementation(project(":services:ingest-service"))
	}

	def buildBaseModel = tasks.register("buildBaseModel", BuildBaseModelTask)
	buildBaseModel.configure {
		workspaceFile = project.layout.buildDirectory.file("resources/model/workspace.json")
	}
	def baseModel = buildBaseModel.flatMap { it.workspaceFile }

	def scanComponents = tasks.register("scanComponents", ScanComponentTask)
	scanComponents.configure {
		workspaceFile = baseModel
		outputFile = project.layout.buildDirectory.file("resources/model/workspace.json")
	}
	def completeModel = scanComponents.flatMap { it.outputFile }
    ```
1. Define a task in each service to scan its own components, then call each of these tasks in sequence from the documentation module while providing the workspace as an `InputFile`
    - This way it would be possible to use the classpath and source directory of each service directly
    - It would also mean the code to create a projects model would be contained within the project
    - The documentation module would have to call the task of another module and provide it an `InputFile`
    - Once the task would be done it would have to get the `OutputFile` and pass it on to remaining services or finalize the model if there are no more services to add
    - So far it seems like this isn't possible with Gradle though

Have you tried to set up such a project with Gradle before or do you have any pointers on how I could resolve this issue?

**Comment by simonbrowndotje** [comment]
I'm not a Gradle expert, but the simplicity of dealing with smaller (and isolated) classpaths would make me favour option 2.

**Comment by MLNW** [comment]
That would also be my preferred option but it seems like Gradle does not support this.

Actually a third option may be possible:

3. Create a configuration and related artifacts for modules that should add component scans to the model
    - This is based on https://docs.gradle.org/current/userguide/cross_project_publications.html#sec:simple-sharing-artifacts-between-projects
    - One would create a consumable artifact of type component scan which in the end is the base workspace enhanced with the found components
    - Each service would create these component scans
    - The documentation module would then depend on all component scans
    - In a task it would then take all scans and merge the JSON into a single workspace
    - But there is no merge functionality yet on the `WorkspaceUtils` class and I am not sure how hard it would be to implement this

**Comment by simonbrowndotje** [comment]
If you write the workspace JSON to a single location (so there's no need for input files and output files), why can't you just create a top-level task that calls a task in all subprojects? For example -> https://stackoverflow.com/questions/26509427/execute-gradle-task-on-sub-projects

(again, I'm not super proficient with Gradle, so I might not be understanding what you're having problems with)

**Comment by MLNW** [comment]
I'm rather new to Gradle so I wasn't aware one can actually use the `${rootProject}` variable to store build artifacts in the root project build dir instead of the project build dir.
With that I should get closer to what I want to accomplish.

I will experiment further in the next few days. I'll let you know if I progress further on the issue.

**Comment by MLNW** [comment]
I finally made it all work!

The `model` module now has a set of tasks to build the base model (create the persons, systems, and containers), scan containers for components, and generate diagrams from the finalized workspace, which is stored in the build directory of the `rootProject`.

The whole thing is tied into the `base` Gradle plugin lifecycle with `build` and `clean`:

```groovy
plugins {
    id("base")
}

ext {
    modelDir = rootProject.layout.buildDirectory.dir("resources/model")
    diagramsDir = modelDir.get().dir("diagrams")
    workspaceFile = modelDir.get().file("workspace.json")
}

def buildBaseModel = tasks.register("buildBaseModel", BuildBaseModelTask)
buildBaseModel.configure {
    inputFile = workspaceFile
}

def scanComponents = tasks.register("scanComponents")
scanComponents.configure {
    dependsOn(provider {
        rootProject.getTasksByName("scanComponentsTask", true)
    })
    mustRunAfter(buildBaseModel)
}

def generateDiagrams = tasks.register("generateDiagrams", GenerateDiagramsTask)
generateDiagrams.configure {
    inputFile = workspaceFile
    outputDir = diagramsDir
    mustRunAfter(scanComponents)
}

build.configure {
    dependsOn(buildBaseModel)
    dependsOn(scanComponents)
    dependsOn(generateDiagrams)

    shouldRunAfter(clean)
}

task cleanModel(type: Delete) {
    delete modelDir
}

task cleanDiagrams(type: Delete) {
    delete diagramsDir
}

clean.dependsOn(cleanModel)
```

Now all that's left to do is add `scanComponentsTask` task definitions to each container. For this I used the `JavaExec` task type to call a separate `main` function:

```groovy
task scanComponentsTask(type: JavaExec) {
    group = "Execution"
    description = "Scan components and add to model"
    classpath = sourceSets.main.runtimeClasspath
    main = ...
    args(rootProject.layout.buildDirectory.file("resources/model/workspace.json").get().toString())
}
```

It would probably be possible to encapsulate some of these concepts in a custom Gradle plugin to ease setting up multi-module Gradle projects but for now, I am happy with the solution detailed above.
