### ISSUE TITLE
Possibility to wrap persons and software systems in an enterprise

### ISSUE THREAD

**Issue by jgautheron** [structurizr/java#161]
With the DSL I could do that:

```
enterprise "companyName" {
    supportStaff = person "Customer Service Staff" ""
    companySoftwareSystem = softwareSystem "Software System" "" {
        ...
    }
}
```

With Java I see that I can do:

```java
model.setEnterprise(new Enterprise("company"));
```
But I don't see a way to wrap persons/software systems/... inside that enterprise.

Did I miss something?
Thanks.

**Comment by simonbrowndotje** [comment]
This is the magic that puts people "inside" the enterprise -> https://github.com/structurizr/dsl/blob/master/src/main/java/com/structurizr/dsl/PersonParser.java#L34

(just set the `location` property of your people and software systems to `Location.Internal`)

**Comment by jgautheron** [comment]
That works, thanks!
I have a similar issue with groups, that I really appreciate to group together a service and its direct dependencies (databases...), it gives a clearer view, especially with `autoLayout`.

```
group "Service 1" {
    service = component "Service 1"
    database = component "Database"
    cache = component "Cache"
}
```
I don't see any `setGroup` exposed on the `Component` object.
Even though I see it here:
https://github.com/structurizr/dsl/blob/master/src/main/java/com/structurizr/dsl/ComponentParser.java#L41

**Comment by jgautheron** [comment]
OK the issue was related to the outdated version in https://github.com/structurizr/java-quickstart (1.3.5), I updated it to 1.8.0 and the method is there!
Thanks again.
