### ISSUE TITLE
Styling of response relationship in dynamic view

### ISSUE THREAD

**Issue by alleknalle** [structurizr/java#162]
Would it be an idea to be able to style a response relationship in a dynamic view? This way you can visually show the difference between the 'regular' relation direction and the response.

**Comment by simonbrowndotje** [comment]
There's an undocumented way to do this, although the resulting style doesn't show on the diagram key ... you can add a style for the `Relationship/Response` tag as [demonstrated here](http://structurizr.com/dsl?src=https://gist.githubusercontent.com/simonbrowndotje/4c8b2fcb79a333fa15a746375415b77a/raw/1b477610b396002e0458183527dbe77a676fcba5/gistfile1.txt).

**Comment by alleknalle** [comment]
Great thanks!
