### ISSUE TITLE
Generated json files cluttering workspace

### ISSUE THREAD

**Issue by blundell** [structurizr/java#17]
Each time I create a diagram it is generating this json file, which is fine - however it is generating it in the base directory of my project. It should really be generated in the base directory of the module. 

i.e. not in `/ore` but inside `/diagrams`

Right now I have to append the projects .gitignore to stop these being committed but this means the project then knows about structurizer, I would much rather have edit the specific .gitignore inside of `/diagrams` and keep everything to do with structurizer inside here. 

![output](https://cloud.githubusercontent.com/assets/655860/12050053/5640bd06-aee7-11e5-83f5-3f0d61862384.png)

**Comment by simonbrowndotje** [comment]
By default, those JSON files are stored in the current working directory. If changing the current working directory is not an option, you can change this behaviour by calling the setWorkspaceArchiveLocation() method on your StructurizrClient instance: https://github.com/structurizr/java/blob/master/structurizr-client/src/com/structurizr/api/StructurizrClient.java#L117

Passing a null value will stop the JSON files from being created.

Does that help?

**Comment by blundell** [comment]
:+1: great I'll use `setWorkspaceArchiveLocation`
