### ISSUE TITLE
Implied Relationships not inheriting tags anymore

### ISSUE THREAD

**Issue by juanrferia** [structurizr/java#170]
After the latest update I realized implied relationships created by CreateImpliedRelationshipsUnlessSameRelationshipExistsStrategy strategy are not inheriting tags anymore.
As a result, when a view adding or removing relationships by tag, that does not make any effect with implied relationships.

I believe that is related to latest changes on this:
https://github.com/structurizr/java/blob/075db91cbee4bb95f21e768bff8bbfb589870e60/structurizr-core/src/com/structurizr/model/CreateImpliedRelationshipsUnlessSameRelationshipExistsStrategy.java#L22

**Comment by simonbrowndotje** [comment]
That's correct. If you're adding/removing elements by tag via the Java library directly (i.e. not via the DSL), you'll need to check the "linked relationship".
