### ISSUE TITLE
No relationship tag in implied relationships 

### ISSUE THREAD

**Issue by ICEMANno1** [structurizr/java#174]
Hi Simon, 
if I see it right, sometimes you create a relationship without the relationship tag (e.g. implied relationships) https://github.com/structurizr/java/blob/f85ed233c565c9c2da40b4aeed78f2a539ea1c97/structurizr-core/src/com/structurizr/model/Model.java#L240-L248
Is there a reason? Does this harm any structurizr tooling logic?

I'm just wondering :)
Regards
Dominik

**Comment by simonbrowndotje** [comment]
Correct, yes ... you can read more about this in [issue 167](https://github.com/structurizr/java/issues/167).

**Comment by ICEMANno1** [comment]
Ahh, k. Seems like not effect anymore. Even cli seems to work, not like the comment in the issue states. Or Amy I mistaking and the cli shouldn't work yet?

**Comment by simonbrowndotje** [comment]
Yes, all of the Structurizr tooling was modified to take this change into account.

**Comment by ICEMANno1** [comment]
Great 👍 Thanks!
