### ISSUE TITLE
Description Uniqueness

### ISSUE THREAD

**Issue by ICEMANno1** [structurizr/java#175]
Hey simon, I bumped into this https://github.com/structurizr/java/blob/783ff48f0251ceea966e6fd61397913b5837e441/structurizr-core/src/com/structurizr/model/Model.java#L570-L577 a couple of times and am now wondering:
- why is this required (feel free to ignore this, I'm just nosy)
- how can I avoid this, since I generate a lot of relationships across a lot of containers & components

Thanks
Dominik

**Comment by simonbrowndotje** [comment]
> why is this required

Let's ask the question the other way around ... why would you want a diagram with two identical relationships between a pair of elements?

**Comment by ICEMANno1** [comment]
Nice one 😅 I can see your experience.

Background is, that I'm taking e.g.  OIDC Client config incl. audience list as realtionship source & destination. I can then add HTTP as technology but would leave the description empty, so the developers can add this later. This results in plenty of empty string descriptions.

**Comment by ICEMANno1** [comment]
Ok, I figured out what my problem was: me 🙈 At the end of my generation tool, it just takes all info an generates the deployment nodes. Here it was "dumb" and just did add again. Now I delete first and regenerate and everything is fine 😅
