### ISSUE TITLE
Handling of view exceptions

### ISSUE THREAD

**Issue by Avega-DanDie** [structurizr/java#182]
Good evening,
we use Stucturizr excessively to visualize our IT architecture landscape. 
With the updates of the library some time ago, we have also observed the announced behaviour that Structurizr has become more restrictive.
Unfortunately, it irritates our users that errors are displayed both in the IDE (IntelliJ, see screenshot) and in the logs on the build server. However, the workspace is published nevertheless. 
Due to the large number of workspaces, the complex relationships and the fact that a lot of code is generated automatically, it will hardly be possible to correct all those findings manually. 
Therefore, my question is whether there is a way to at least output the errors as "warning" or to catch them in another way. Simply wrap the initViews() method with a try/catch block around doesn't have an effect. 
I'm aware that ignoring those faults in the defined views is against the Structurizr policy.
We are currently using version 1.16.1 of the client library.
Thanks in advance for any advice.

Dani

<img width="759" alt="Bildschirmfoto 2022-11-23 um 22 23 24" src="https://user-images.githubusercontent.com/71312249/203648514-b2da8b12-77a3-4309-853a-cfe0988b5be8.png">

**Comment by simonbrowndotje** [comment]
> Therefore, my question is whether there is a way to at least output the errors as "warning" or to catch them in another way. > Simply wrap the initViews() method with a try/catch block around doesn't have an effect.
> I'm aware that ignoring those faults in the defined views is against the Structurizr policy.

I don't really know what you mean by `initViews()` and `against the Structurizr policy` I'm afraid. If you can share a code sample that causes the errors, then perhaps I can make some suggestions.

**Comment by Avega-DanDie** [comment]
Hello Simon
thank you very much for your fast response. 
Sorry for expressing me so poorly. What I meant by "it's against the Structurizr policy" is, that Structurizr is becoming more restrictive and doesn't just ignore faulty views. It's a good way that helps increasing the quality of the view compositions.

Regarding the wrapping I mentioned, I have to apologize. The initViews method, I have was pointing to is still on our side and doesn't belong to any Structurizr class. But after digging a bit deeper, I found the following snippet in the mapping strategy class:
```
static void invokeAddElementExcludingRelationshipsOnView(final View view, final Element element) {
        try {
            final Method addElement = View.class.getDeclaredMethod("addElement", Element.class, boolean.class);
            addElement.setAccessible(true);
            final boolean includingRelationships = false;
            addElement.invoke(view, element, includingRelationships);
        } catch (NoSuchMethodException | IllegalAccessException | InvocationTargetException | ElementNotPermittedInViewException e) {
            LOG.error("Can't execute addElement() of view " + view.getKey(), e);
        }
    }
```

Here, the exception is caught, but still displayed as error in the run window/console. Might this relate to how the method is invoked? I suppose, it's been implemented this way, because the visibility of addElement() on the view class is set to protected.

As said, it's not a good coding style to just suppress exceptions, but there have been multiple request from users, if there is a way to "mitigate" the representation of such issues since the workspace is created/updated nevertheless.
Thanks again for your time and support.
Best regards,
Dani

**Comment by simonbrowndotje** [comment]
Have you tried adding `IllegalArgumentException` to your catch block? 

Source -> https://github.com/structurizr/java/blob/master/structurizr-core/src/com/structurizr/view/View.java#L281

**Comment by simonbrowndotje** [comment]
Actually, I take that back, it's not going to catch the specific exceptions you're seeing. Those "a child of X" exceptions are thrown because you're trying to add elements to a view where they don't belong, and the framework is stopping you doing this, because that particular combination of elements can't be rendered. For example, it will prevent you adding the parent software system of a container to a container view, if the container itself is already present in the view.

So you have two options:

1. Blindly add elements to the views and accept that you're going to see error messages. The `addElement()` method is hidden for a reason, and it's not a part of the public API.
2. Be a little more intelligent about how you're creating views, and use the appropriate `add(SoftwareSystem)`, `add(Container)`, etc methods on the specific `View` implementations.

**Comment by Avega-DanDie** [comment]
Thanks for your answer. That's very much appreciated and I will forward it to our architects. I think, it has been quite comfortable for them to just add lots of elements and let the library do the sanity check. 
But also, I will check if I can refactor the code in order to implement the second option you mentioned. 
Thanks again for your support.
Have a great day.
DaniD
