### ISSUE TITLE
Case-insensitive names: bug of feature?

### ISSUE THREAD

**Issue by linkrope** [structurizr/java#183]
The demo page fails to render this workspace:
```
workspace {
    model {
        system = softwareSystem "System" {
            container "container" {
            }
            container "Container" {
            }
        }
    }

    views {
        container system {
            include *
            autolayout lr
        }

        theme default
    }
}
```

Structurizr Lite prints an unhelpful `WorkspaceValidationException` that a container named "container" already exists.

The Language Reference tells that keywords are case-insensitive, but tells nothing about names.

**Comment by simonbrowndotje** [comment]
TODO: Look into why the [Model.checkNameIsUnique()](https://github.com/structurizr/java/blob/master/structurizr-core/src/com/structurizr/model/Model.java#L546) method is using a case-insensitive check.
