### ISSUE TITLE
Parameter names for Model.addPerson

### ISSUE THREAD

**Issue by KKorzuno** [structurizr/java#184]
without location: String name (and String description)
with location: arg1, arg2, arg3 (location being first).

**Comment by simonbrowndotje** [comment]
The parameter names are all documented -> https://github.com/structurizr/java/blob/master/structurizr-core/src/com/structurizr/model/Model.java#L137 ... what exactly are you asking with this issue?

**Comment by KKorzuno** [comment]
I did not do coding for a longer while, so I might be saying silly things. 
This is a screenshot from VSCode. It recognises parameter names on all other constructors but not the one with 3 input values. And it does it consistently. Maybe a VScode bug of some sort.
![person](https://user-images.githubusercontent.com/1334346/209813629-2ae6933b-ec4b-4e73-a69a-3551b16d216f.png)
