### ISSUE TITLE
DSL <-> Java model implementation differences

### ISSUE THREAD

**Issue by KKorzuno** [structurizr/java#189]
I played a few days with DSL. Then I decided it is not enough and started playing with java modelling. It was a bit surprising to see that the implied relationship strategy is different between the two. In the DSL it is "inherit" (it seems in both directions) and in java "do nothing".  Do not know if this is working as expected, but would be good to explain somewhere -> if you used DSL, please consider doing _this_ to keep the behavior the same.

**Comment by simonbrowndotje** [comment]
The DSL is a wrapper around the Java library, with some common defaults applied ... one of those being the implied relationships functionality, and is described at [DSL cookbook - Implied relationships](https://github.com/structurizr/dsl/tree/master/docs/cookbook/implied-relationships).

Copying this line will replicate that behaviour in the Java library -> https://github.com/structurizr/dsl/blob/master/src/main/java/com/structurizr/dsl/WorkspaceParser.java#L22

```
workspace.getModel().setImpliedRelationshipsStrategy(new CreateImpliedRelationshipsUnlessAnyRelationshipExistsStrategy());
```
