### ISSUE TITLE
Allow named colors

### ISSUE THREAD

**Issue by dgutson** [structurizr/java#192]
Please allow named colors (maybe as pre-defined constants), at least [the basic HTML colors](https://en.wikipedia.org/wiki/Web_colors#Basic_colors), or https://www.rapidtables.com/web/color/RGB_Color.html,

**Comment by dgutson** [comment]
Thanks, I thought it was easier and future extensible to have a default pre-included dsl with useful pre-defined symbols (as a std structurizr lib), such as constants for the colors, rather than modifying the code. That's why we were going to contribute it, but up to you.
Could you please update the language reference too?

**Comment by simonbrowndotje** [comment]
> Could you please update the language reference too?

Yes, the DSL language reference (and DSL parser error messages) will be updated after `structurizr-client:1.18.0` has been released to Maven Central, and [the dependency](https://github.com/structurizr/dsl/blob/master/build.gradle#L12) is updated.

**Comment by dgutson** [comment]
Thanks!

**Comment by dgutson** [comment]
any chance to turn colors case-insensitive? as the [General Rules](https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#general-rules) state:
> * Keywords are case-insensitive (e.g. you can use `softwareSystem` or `softwaresystem`).
