### ISSUE TITLE
Exporting workspace authored with structurizr java to dsl

### ISSUE THREAD

**Issue by skiddow123** [structurizr/java#197]
Is there a way of exporting a workspace authored with the java library to its dsl equivalent without using the API Client?

**Comment by simonbrowndotje** [comment]
Yes, you can paste the JSON version of your workspace into https://structurizr.com/json, click `Render`, then click the `DSL` tab. Some caveats though:

1. This was only designed to help people migrate to the DSL from the browser-based workspace editor, so it may not work correctly.
2. The DSL it generates is quite verbose, but can be a useful starting point if you're looking for migrate away from the Java library to the DSL.
