### ISSUE TITLE
Allow Relationship views to contain URLs, which then get used as links on dynamic views and sequence diagrams

### ISSUE THREAD

**Issue by ambition-consulting** [structurizr/java#214]
### Description

I have build an automatic sequence diagram generator from Java code. I would like to link every sequence diagram call to the corresponding lines of code via a specific URL.

### Priority

Low

### Resolution

I have no budget, please add this feature for free

**Comment by ambition-consulting** [comment]
Thank you 👍

**Comment by dzharikhin** [comment]
also it would be nice to be able to add tags to relations on dynamic view
This can make dynamic views more expressive
