### ISSUE TITLE
Support for parent by template

### ISSUE THREAD

**Issue by perottobc** [structurizr/java#220]
### Description

Default parent and pom.xml is spring-boot, created by spring-initializr.
This makes support for generating libraries troublesome, where you typically want to completely control the pom-generation. 
Suggestion, add the following to settings ->
"useSpringInitializr": false,

The standard use of templates will fix the rest, by adding your template for a library, eg
    "templates": [
        "library/nexus-release-support"
    ],

### Priority

I have no budget and there's no rush, please add this feature for free

**Comment by simonbrowndotje** [comment]
I don't really understand what you're asking for, but you're welcome to submit a PR.

**Comment by simonbrowndotje** [comment]
No response ... closing as stale.

**Comment by perottobc** [comment]
Sorry Simon, I managed to post on the wrong project :-) 
Structurizr is great, I use it to generate diagrams from a log, where the log contains stacktraces that are analyzed an converted to modules and relationships.
