### ISSUE TITLE
AbstractReflectionsComponentFinderStrategy only allows for dependencies in the scanned package

### ISSUE THREAD

**Issue by devnoo** [structurizr/java#25]
I added some components from 3rd party libraries that are used by a lot of spring controllers, and then i scan for the spring controllers. I expected the controllers to be linked the controller but while they all show up in the diagram there is no usage in between. Looking at the code of AbstractReflectionComponentFinderStrategy it seems it only will link components that reside in the scanned package. It would really be useful to allow it to add dependencies to all the already registered components.  Or at least make it configurable.
so this if in the addEfferentDependencies is causing this behavior:

`   if (referencedTypeName.startsWith(componentFinder.getPackageToScan())) {

                    Component destinationComponent = componentFinder.getContainer().getComponentOfType(referencedTypeName);
                    if (destinationComponent != null) {
                        if (component != destinationComponent) {
                            component.uses(destinationComponent, "");
                        }
                    } else if (!referencedTypeName.equals(implementationType) && depth < 10) {
                        addEfferentDependencies(component, referencedTypeName, ++depth);
                    }
                }`

**Comment by simonbrowndotje** [comment]
If you create a ComponentFinder for the third-party components first (and call findComponents), and then create a second ComponentFinder for your own components, you should see the relationships show up.

**Comment by devnoo** [comment]
ok,  added the component manually to the container, before adding the
component finder for spring, so instead of doing this, i have to add a
component finder that "finds",(or just adds ) the 3rd party components.
Thanx

**Comment by devnoo** [comment]
it only works when i do it the other way around,

So first i define scan my own components, then i add the 3rd party finder, and probably only because i don't extend the AbstractReflectionsComponentFinderStrategy  for the 3rd party component Finder.
`

ComponentFinder axonComponentFinder = new ComponentFinder(
	containers.webApplication, "org.axon",
	new AbstractNamingConventionComponentFinderStrategy() {
		@Override
		protected boolean matches(Class<?> type) {
			return type.equals(DefaultCommandGateway)
		}
	}
);


ComponentFinder componentFinder = new ComponentFinder(
	containers.webApplication, "nl.devnoo",
	new CustomComponentFinderStrategy()
);

componentFinder.findComponents();
axonComponentFinder.findComponents()
`

if i change the order of the find components it won't put the dependencies.
Seeing the code in the AbstractReflectionsComponentFinderStrategy this seems logical, because it gets the components from the container and then intentionally excludes the components that are no in the current package to scan.

**Comment by simonbrowndotje** [comment]
I'm been mulling this over and the following check in findEfferentDependencies seems unnecessary, especially if previous component finders have found components in different packages.

`if (referencedTypeName.startsWith(componentFinder.getPackageToScan())) {`

I'll create some test cases to simulate what you're doing.

**Comment by simonbrowndotje** [comment]
That restriction has now been removed; you should be able to use multiple component finders in any order. Thanks Job.

**Comment by devnoo** [comment]
Yeah was exactly the if statement i was wondering about. Thanks for the
quick reaction.
