### ISSUE TITLE
Component finder results in nullpointer in version 0.6

### ISSUE THREAD

**Issue by GuidoDechamps** [structurizr/java#27]
For a quick test i just wanted to scan everything on a small pet project. So i did:
`new NameSuffixComponentFinderStrategy("") `

Unfortunately this results in 

` java.lang.NullPointerException
	at com.structurizr.componentfinder.ComponentFinder.foundComponent(ComponentFinder.java:39)`

Its ok for me if an empty string does not return anything. It wasn't a valid regex or anything.
But a nullpointer seems less then ideal to me ;-)
But then i looked a little deeper and it seems that the nullpointer is the result of an anonymous inner class. The empty suffix is allowed. It matches everything. But matching the inner class results in an error due because `type.getCanonicalName()` is null when type is an inner class.

**Comment by simonbrowndotje** [comment]
Thanks Guido ... this is fixed in v0.7.
