### ISSUE TITLE
[DSL] A relationship between ... already exists, property to ignore this

### ISSUE THREAD

**Issue by neopaf** [structurizr/java#284]
### Description

Two different people create two separate systems in two different git repos.

They both define that they communicate:
* Architect of A defines that A->B "action".
* Architect of B defines that A->B "action" (action is the same, obviously).

When I include both dsl files into my space to give readers an overview of all systems of my department, dear Structurizr complains of a (complete) duplicate.

Please consider a **property** to ignore these conflicts: say, `ignoreDuplicateRelationships`, default `false`.

Then each A and B architects could have errors in case they have local conflicts.
But for overall picture one could turn `ignoreDuplicateRelationships`=`true` and be happy?

### Priority

I have no budget and there's no rush, please add this feature for free

### More information

(thanks for AWESOME product!)

**Comment by simonbrowndotje** [comment]
This is working as designed, and I'd rather not start adding flags to disable various validation rules. You're welcome to add that functionality to your own fork though.

I'd recommend looking at the [enterprise examples](https://github.com/structurizr/examples/tree/main/enterprise) that show a better way to generate landscape view of a collection of systems.
