### ISSUE TITLE
No Person to Person relationship

### ISSUE THREAD

**Issue by GuidoDechamps** [structurizr/java#31]
In my dynamic diagram i want to display an interaction between two persons. This is not yet possible.

**Comment by simonbrowndotje** [comment]
My immediate thought is that this isn't something I want to support. What's the relationship you're trying to model?

**Comment by GuidoDechamps** [comment]
User A triggers action in system A. Results in change in system B.  This results in user B performing an action in the real world that triggers User C that triggers action in system C.

**Comment by simonbrowndotje** [comment]
Right, I see ... I'm planning to add an "Enterprise Context" diagram in the future so I'll add the person-person relationships. Any thoughts on what the method on the Person class should be called?

**Comment by GuidoDechamps** [comment]
Hmmm, performAction? does?

```java
Person employee;
Person boss;

employee.performsAction("sendEmail",boss);
employee.performsAction("telephone",boss);
//or
employee.does("sendEmail",boss);
employee.does("telephone",boss);
```

**Comment by simonbrowndotje** [comment]
How about "interactsWith" ... e.g. person1.interactsWith(person2, "Sends an e-mail to")?

**Comment by GuidoDechamps** [comment]
Even better! It clearly states that it has a target of interaction.

**Comment by simonbrowndotje** [comment]
"interactsWith()" it is then ... this code is now in the repo and you can see an example at:

- https://github.com/structurizr/java/blob/master/structurizr-examples/src/com/structurizr/example/core/WidgetsLimited.java#L37
- https://structurizr.com/public/14471#enterpriseContext

**Comment by GuidoDechamps** [comment]
Ok. Solved for me.
