### ISSUE TITLE
Publication of the structurizr-dot artifact in a maven repository

### ISSUE THREAD

**Issue by SR-G** [structurizr/java#34]
As far as i can tell, i can't find the "structurizr-dot" jar artifact published anywhere [*], could it be possible to activate the publication of this submodule for the next release ?
(i've seen that there are really not a lot of code in the module, but it would be cleaner to just re-use it)

[\* : not found here http://jcenter.bintray.com/com/structurizr/ for example ]

**Comment by SR-G** [comment]
Okay have just seen that you have an external lib/ dependency not available in any maven repository, that's probably why you're stuck not publishing the structurizr-dot artifact at this time ...

**Comment by simonbrowndotje** [comment]
Good news ... the dot-diagram library is now available on Maven, so I'll publish the structurizr-dot  jar at the next release (which will be happening soon).

**Comment by egulias** [comment]
@simonbrowndotje great news! I was looking to this issue while writing you on twitter. Basically I couldn't compile 
`import com.structurizr.io.dot.DotWriter` because the code wasn't even downloaded.

Happy to know it will be fixed.
