### ISSUE TITLE
Ordering of replicated relationships in deployment environment is non-deterministic

### ISSUE THREAD

**Issue by goto1134** [structurizr/java#362]
### Description

Running tests in https://github.com/goto1134/structurizr-d2-exporter, I face multiple false-negative results.

The tests are end-to-end: given a structurizr workspace.dsl the code produces a d2 output and check if it is the same as expected.

The diffs for failed tests usually contain the same data but a different order of relationships added:
![image](https://github.com/user-attachments/assets/5d964224-6ed4-42c7-8863-ef3b4c49644e)
See an example here: https://github.com/goto1134/structurizr-d2-exporter/pull/143/checks?check_run_id=33778947846

Please provide a deterministic order of relationships in the workspace to be exported.

### Priority

I have no budget and there's no rush, please add this feature for free

**Comment by simonbrowndotje** [comment]
`RelationshipView` instances are stored in a `TreeSet`, so I'm not sure how you're seeing non-deterministic ordering. If this was the case, my own exporter tests should exhibit the same failing behaviour, but they don't.

- https://github.com/structurizr/java/blob/master/structurizr-core/src/main/java/com/structurizr/view/ModelView.java#L38

Perhaps it's related to `view.relationships.associateBy { it.id }`, which seems to use a `LinkedHashMap`?

- https://github.com/goto1134/structurizr-d2-exporter/blob/main/lib/src/main/kotlin/io/github/goto1134/structurizr/export/d2/D2Exporter.kt#L97

**Comment by goto1134** [comment]
@simonbrowndotje, thank you; I will check that!

**Comment by goto1134** [comment]
@simonbrowndotje, the code you referenced is only used for animations, and the workspace in the provided test does not use any animation in it. So it can't be it.

Do you think I could gather some examples for you?

**Comment by simonbrowndotje** [comment]
I've just released v3.2.1 that should resolve this for you ... it turns out that it was the process of replicating relationships when software system/container instances were added to deployment nodes that was non-deterministic, rather than calling `ModelView.getRelationships()`.
