### ISSUE TITLE
SourceCodeComponentFinderStrategy: make file encoding configurable

### ISSUE THREAD

**Issue by hbrands** [structurizr/java#47]
It appears to my that SourceCodeComponentFinderStrategy only supports UTF-8 as file encoding.
As a default that's the right thing to do.
But it would be nice to be able to specify the encoding, for example we have a case where "iso-8859-1" is used in the project.
In the implementation of #runJavaDoc in SourceCodeComponentFinderStrategy, you could pass the configured file encoding via the "-encoding" command line parameter to the doclet.

**Comment by simonbrowndotje** [comment]
You can now call setEncoding() to do this ... let me know if that does the trick.
