### ISSUE TITLE
Web interface ignores Papersize

### ISSUE THREAD

**Issue by jflalande** [structurizr/java#54]
I have trouble using the method sePaperSize(). When reloading the Structurizr workspace, the paper_size seems to ignore the java calls I made:
       
        ` SystemContextView contextView = views.createSystemContextView(irma, "Overview", "Kharon architecture");
        contextView.addAllSoftwareSystems();
        contextView.add(user);
        contextView.setPaperSize(PaperSize.A5_Landscape);

        // Software view
        SystemContextView contextView = views.createSystemContextView(irma, "Overview", "Kharon architecture");
        contextView.addAllSoftwareSystems();
        contextView.add(user);
        contextView.setPaperSize(PaperSize.A5_Landscape);

        // Who view
        SystemContextView whoView = views.createSystemContextView(irma, "Who", "Kharon architecture");
        whoView.addAllSoftwareSystems();
        whoView.addAllPeople();
        whoView.setPaperSize(PaperSize.A5_Landscape);`

and I always get an A4 Portrait on the website, except for the 1st diagram (SystemContext) that seems to take the call into account the A5 landscape call...

**Comment by simonbrowndotje** [comment]
That's been bugging me recently too ... it's this line that is copying the paper size from the online version of the workspace -> https://github.com/structurizr/java/blob/master/structurizr-core/src/com/structurizr/view/View.java#L262

I will remove it. :-)

**Comment by jflalande** [comment]
In fact, it is unclear who is handling paper size: I just realized that the paper size is saved by the web interface (when hitting the record button). Thus, is the paperSize controlled by web interface or the code ? I suspect that this information should be retrieved by the server and should be overwritten by the code in case of a call to .setPaperSize().

**Comment by simonbrowndotje** [comment]
I removed that line of code and then reverting the change shortly afterwards, because I do want the paper size copied across when the workspace is merged. However, I've put a check around this to only copy the paper size from the remote workspace if the paper size has not been set.
