### ISSUE TITLE
Spring Pet Clinic demo doesn't have public controllers

### ISSUE THREAD

**Issue by Zaijo** [structurizr/java#57]
I was following tutorial at https://github.com/structurizr/java/blob/master/docs/spring-petclinic.md, but I was still getting component view without controllers, until I found that `SpringComponentFinderStrategy` by default ignores non-public classes.

Since https://github.com/spring-projects/spring-petclinic/commit/83ff9a50e378529993f4f772457dd24791b46438 controllers in pet clinic are not public which causes trouble following the tutorial for Pet Clinic. 

Maybe referencing fixed revision in the tutorial could help.

**Comment by simonbrowndotje** [comment]
Is this with a "git checkout 95de1d9f8bf63560915331664b27a4a75ce1f1f6"?

**Comment by Zaijo** [comment]
In https://github.com/spring-projects/spring-petclinic/commit/95de1d9f8bf63560915331664b27a4a75ce1f1f6 (2016-01-30) as you ask for example `PetController` is public. The change I am writing about happened on (2016-11-10), wich is later than the version you asked for.

**Comment by simonbrowndotje** [comment]
I'm not sure that I understand what you're asking for. Does the PetClinic tutorial work as instructed?

**Comment by Zaijo** [comment]
No it doesn't work for me.

I am able to upload all diagrams exactly as expected **except for component diagram**, which is **missing all Controllers**. I looked at the javadoc for `SpringComponentFinderStrategy` and found out, that it ignores all non-public classes. I looked into PetClinic source (which I checked out today - fresh master) and all controller were declared package-private (no modifier).

I say: Tutorial is missing either:
- notice in tutorial, that it works only on commits before https://github.com/spring-projects/spring-petclinic/commit/83ff9a50e378529993f4f772457dd24791b46438
- or a line of code, using `springComponentFinderStrategy.setIncludePublicTypesOnly(false);` which is what I ended up with.

**Comment by simonbrowndotje** [comment]
Understood. The instructions for cloning the PetClinic repo do include a specific revision though -> https://github.com/structurizr/java/blob/master/docs/spring-petclinic.md#1-clone-and-build-the-spring-petclinic-code

**Comment by Zaijo** [comment]
Oh! My bad. I followed the link to PetClinic repo and basically skipped the rest of the code area, with "I know how to checkout" in my mind.

**Comment by simonbrowndotje** [comment]
No problem! I'll add a note to explain why the checkout is needed. :-)

**Comment by simonbrowndotje** [comment]
That's now done.

**Comment by Zaijo** [comment]
OK, for me that fixes the problem.
