### ISSUE TITLE
Diagram writer interface to be able to produce multiple files

### ISSUE THREAD

**Issue by Zaijo** [structurizr/java#61]
In case of PlantUML, the processor to image expects to receive one diagram at a time.

Current interface of writers doesn't allow returning multiple diagrams separately. I had to split the string on "@startuml" line and save as individual files.

**Comment by simonbrowndotje** [comment]
I might change the name before a Maven release (and it needs some tests), but I've added a toPlantUML() method that returns a collection of Strings, one per diagram -> https://github.com/structurizr/java/blob/master/structurizr-core/src/com/structurizr/io/plantuml/PlantUMLWriter.java#L60

**Comment by Zaijo** [comment]
Very well, that does the job (I only looked at the method signature). Thanks.

Well, how do you close issues like this? 

- Accepted to master -> done?

or 

- Part of a new release -> done?
