### ISSUE TITLE
Person with Internal Location appearing as External in a Container View

### ISSUE THREAD

**Issue by nanachimi** [structurizr/java#65]
I have the following code which generate a `context` and `container view`. Unfortunaly the objects `distributor` and  `admin` type `Person` doesn't  appear inside the enterprise context of a  container diagram but in a context diagram it does.

See my code snippet:

```java
Workspace workspace = new Workspace("MyPlatform", "My online platform");
Model model = workspace.getModel();
Person distributor = model.addPerson(Location.Internal,"Distributor", "A distributor");
Person admin = model.addPerson(Location.Internal,"Admin", "An Admin");
SoftwareSystem platform = model.addSoftwareSystem(Location.Internal, "My Platform", "A platform.");
administrator.uses(platform, "Manage all accounts");
...
Container distributorApplication = platform.addContainer("Distrib. App", "A distributor mobile app" "Android");
distributor.uses(distributorApplication, "Uses", "JSON/HTTPS");
Container adminApplication = platform.addContainer("Admin App", "An admin web app", "React");
admin.uses(adminApplication, "Block an account", "JSON/HTTPS");
...

ViewSet views = workspace.getViews();
SystemContextView contextView = views.createSystemContextView(platform, "SystemContext", "A context diagram");
contextView.setPaperSize(A5_Landscape);
contextView.addAllSoftwareSystems();
contextView.addAllPeople();

ContainerView containerView = views.createContainerView(platform, "Container", "A container diagram");
containerView.setPaperSize(A4_Landscape);
containerView.addAllElements();
containerView.addAllSoftwareSystems();
containerView.addAllPeople();

...
```

Any idea how to solve this?

**Comment by simonbrowndotje** [comment]
If you're using structurizr.com to render the software architecture diagrams, the dashed box you see on the container diagram is the software system boundary (see the diagram key for more details), and this is why people sit outside that box.

**Comment by nanachimi** [comment]
yes I used structurizr.com to render. I still don't understand why `contextView` the `admin` and `distributor` are in a system boundary only for a context view and not for a container view. Thanks

**Comment by simonbrowndotje** [comment]
If there is a dashed box on a system context diagram, that represents the "enterprise" boundary, not a software system boundary. This should again be defined on the diagram key.

**Comment by nanachimi** [comment]
Yes there is dashed on a context diagram.
Ok I see. 
> "enterprise" boundary, not a software system boundary
What do you mean exactly by 
> This should again be defined on the diagram key.

**Comment by simonbrowndotje** [comment]
If you press the 'i' key (or click the 'i' toolbar button), you will see the diagram key/legend for the diagram that you are currently viewing. For example...

<img width="931" alt="screen shot 2017-11-18 at 20 37 48" src="https://user-images.githubusercontent.com/1009874/32984542-8742e798-cca0-11e7-9de2-90cbbeed41d6.png">

**Comment by nanachimi** [comment]
Now I got it. The lines are same but have different meaning. Is there any way to change the style of those lines (enterprise and system context boundary) ?

**Comment by simonbrowndotje** [comment]
No. Not yet, anyway.
