### ISSUE TITLE
Pluggable IdGenerator

### ISSUE THREAD

**Issue by roxspring** [structurizr/java#69]
I notice that you've gone to the effort of having an IdGenerator interface as if it were pluggable, but in Model.java the implementation is hard coded to SequentialIdGeneratorStratergy:
https://github.com/structurizr/java/blob/79edfb4d26756818c80b652f213015012f02c180/structurizr-core/src/com/structurizr/model/Model.java#L13

Any objection to this becoming truly pluggable so that alternate implementations can be used?

For example, I repeatedly find myself speculating that it would be useful to have a stable IdGenerator such that as code evolves the same components generate the same ids each run. I'm hopeful that this could have value in linking / merging microservice models into bigger system models; or might have practical value in highlighting changes over time (deleted vs added components)

**Comment by simonbrowndotje** [comment]
Sure, feel free. :-) I was initially undecided about the element/relationship IDs, hence the pluggable interface. I remember doing some testing with a couple of different strategies, so everything *should* work as expected.

**Comment by roxspring** [comment]
Should have referenced this from #70 and #71, now merged.

Any idea when another RC or final version will be cut and pushed to maven central? Would be nice to switch back to using a published release!
