### ISSUE TITLE
Can you provide plantUML source code for all the pictures?

### ISSUE THREAD

**Issue by kaelzhang81** [structurizr/java#75]
Can you provide plantUML source code for all the pictures?thanks！

**Comment by simonbrowndotje** [comment]
Hi, can you elaborate please? What are you looking for/trying to do?

**Comment by kaelzhang81** [comment]
My project is using plantUML to system modeling，and I want to try using c4 model in my project, so I must have the plantUML source code of c4 core diagrams.
Can you provide it to me?my email: zhangy1981@qq.com

**Comment by simonbrowndotje** [comment]
Are you looking for examples of PlantUML diagram definitions? If so, which pictures in particular?
