### ISSUE TITLE
add(Relationship relationship) in DynamicView doesn't work correct

### ISSUE THREAD

**Issue by beatw** [structurizr/java#78]
The method add(Relationship relationship) in DynamicView doesn't work as expected. The relationships don't get a sequence number. And the second attempt to upload the diagram results in an exception. If I use add(Element source, String description, Element destination)  with the information from my relationship object instead all works well...

**Comment by simonbrowndotje** [comment]
You're right, and it really doesn't make sense for that method to be accessible. I will do some refactoring to hide it.

**Comment by simonbrowndotje** [comment]
This has been removed.
