### ISSUE TITLE
Add a SpringWebserviceEndpointFinderStrategy

### ISSUE THREAD

**Issue by mcbeelen** [structurizr/java#82]
I wondering whether or not it would be interesting to add a SpringWebserviceEndpointFinderStrategy, which will look for org.springframework.ws.server.endpoint.annotation.Endpoint annotations.
This would require org.springframework.ws:spring-ws-core:2.4.2.RELEASE to be added as a dependency.

For now I implemented that SpringWebserviceEndpointFinderStrategy as a util in my project, but I willing to contribute it back.
Or is using the AnnotationTypeMatcher the recommended approach?

**Comment by simonbrowndotje** [comment]
Sure, how's this? https://github.com/structurizr/java/commit/aea4ddcddce84a6ada0b1fabaeab00540affe908

**Comment by mcbeelen** [comment]
That works for me after a minor change! 

(I had to change SpringWebserviceEndpointFinderStrategy into SpringWebServiceEndpointComponentFinderStrategy with an upperCase on the S of WebService)

Thank you, Simon.
