### ISSUE TITLE
Model allows multiple Components to exist within a Container

### ISSUE THREAD

**Issue by roxspring** [structurizr/java#83]
`Component` extends `Element` and therefore has a `hashCode()` based purely on `Element.name`. `Container` has a `LinkedHashSet` of `Component` and therefore is limited to one `Component` of any given name. So it seems safe to assume that a Container is designed to only contain one Component of any given name.

`Model.addComponent(..)` methods (unlike `addPerson(..)`, `addSoftwareSystem(..)`, `addContainer(..)`) fails to check the component is new before adding it, thereby overrides the first `Component` of that name with a second. When using `SequentialIntegerIdGeneratorStrategy` both first and second instances get different ids and so both end up in the `Model.elementsById` index (which is weird). When using `MessageDigestIdGenerator` then the both get the same id, the first ends up in the index but the second ends up in the `Container` (which is probelmatic).

A real world example of this can be found using the `ComponentFinder` to find a component that happens to both implement `CrudRepository` AND be annotated `@Repository`.

Suggest that `Model.addComponent(..)` methods are modified to block addition of duplicates in the first place, like their sibling add methods, and that callers are modified to avoid adding duplicates. Will put together a PR along these lines unless I hear objections.

**Comment by simonbrowndotje** [comment]
Thanks, I'm just cleaning up a few things (including documentation), so I'll make this change now.
