### ISSUE TITLE
Java.lang.classnotfound exception when running GettingStarted.java example

### ISSUE THREAD

**Issue by Introvert95** [structurizr/java#94]
Hi,
I am new to structurizr and I am unable to resolve the following issue:
**Code**
 structurizrClient.putWorkspace(WORKSPACE_ID, workspace);
**Error Message**
Apr 17, 2018 11:04:07 AM com.structurizr.api.StructurizrClient putWorkspace
INFO: Putting workspace with ID 38873
Exception in thread "main" java.lang.NoClassDefFoundError: com/structurizr/io/json/JsonWriter
	at com.structurizr.api.StructurizrClient.putWorkspace(StructurizrClient.java:188)
	at com.structurizr.example.GettingStarted.main(GettingStarted.java:50)
Caused by: java.lang.ClassNotFoundException: com.structurizr.io.json.JsonWriter
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 2 more

I downloaded the file and followed all the steps. But, some files still seem to be missing.

**Comment by simonbrowndotje** [comment]
Hi, are you building your own version of the client library from the source code, or using the 1.0.0-RC5 version from Maven Central?

**Comment by simonbrowndotje** [comment]
Just in case you've not seen it, an easier way to get started is to use the java-quickstart project -> https://github.com/structurizr/java-quickstart

**Comment by simonbrowndotje** [comment]
Does the java-quickstart project work when following the instructions here -> https://github.com/structurizr/java-quickstart/blob/master/README.md (i.e. running via Gradle on the command line)?

If not, what's the error that you're seeing?

**Comment by Introvert95** [comment]
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

________________________________

**Comment by simonbrowndotje** [comment]
I've just cloned and run the java-quickstart on my Windows 10 box (also with Java 8), and it works for me. Is there anything unusual about your setup? A proxy server that could be preventing the Gradle zip file from being downloaded? Do you have a .gradle folder in your home directory?

<img width="1156" alt="java-quickstart" src="https://user-images.githubusercontent.com/1009874/38886389-b8a2a592-426d-11e8-8520-c740f9d11179.png">

**Comment by Introvert95** [comment]
I cloned directly using eclipse. A folder was created in the specified directory with all the files in it.


Update: I have tried executing gradlew from the gradle folder and it builds successfully. A .gradle folder is created. But nothing is uploaded to my workspace.

________________________________
